### ISSUE TITLE
Pre-workshop checklist

### ISSUE THREAD

**Issue by olexandr-konovalov** [ccp-codima/2020-01-21-colchester-workshop#1]
* Workshop page
- [x] update location (add room number)
- [x] update the list of instructors
- [ ] update schedule: who teaches what and when: draft at HackMD at https://hackmd.io/@W4sMOUZpT_GtoAgUp_7a9Q/rkjb7t6TS
- [x] create HackMD notepad and put links

* Logistics
- [x] reminder to introduce yourself and familiarise with HackMD before the workshop
- [x] reminder to install software in advance
- [x] optional: organise drop-in sessions to help with installations for local participants
- [ ] reminder about configuring wi-fi 
- [x] order refreshment breaks and lunches
- [x] order workshop dinner
- [ ] put door signs

* Equipment
- [ ] additional projector and screen
- [x] laptop stand (at least a cardboard box)
- [x] extension cables
- [ ] arrange tables
- [x] spare w-fi guest logins
- [x] stickies
- [x] print door signs
- [x] blue-tack for door signs
- [x] whiteboard markers
- [x] Windows virtual machine

**Comment by olexandr-konovalov** [comment]
@AJLitt @jesusmartinez-garcia @mtorpey this checklist is based on the one which we usually use for the Carpentries - just to check if anything escaped our attention.

**Comment by jesusmartinez-garcia** [comment]
@alex-konovalov OK, I have taken care of most of the things and ticked accordingly. I guess we arrange tables at the beginning of each session. It would be good if the instructors are the ones knocking on the door of the classroom at 9.50am (when the previous class finishes) to kick the previous group out on the first day while I'm dealing with registrations. That way you can decide how to move the tables (likely Alastair and Theo Papazachariou can help you with that, I vaguely remember that Gerald teaches at 10am).

Projector: Gerald picks up on Monday afternoon and brings it to me.
Laptop box: I've sent you an e-mail with the box, @alex-konovalov, let me know if it is good.

You've sent the reminder to install software in advance. I have emailed Essex people suggesting I help them on Monday if needed but heard no answer so far.

The door signs will be put on Tuesday morning. They are printed already.

I am not sure what the reminder about configuring wifi is about. Those who do not have eduroam have to electronically fill in a form during registration to get this sorted. I will bring my laptop to that purpose and I think there are extra computers in the foyer where registration takes place.

**Comment by olexandr-konovalov** [comment]
@jesusmartinez-garcia thanks - all looks good to me. I have also ticked a box for Win10 VM, which I have with GAP and SageMath installed - that may be useful to demonstrate or check some OS-dependent things.
